"""HTML report generator using Jinja2."""

from __future__ import annotations

from pathlib import Path

from jinja2 import Template

from argus_lite.models.scan import ScanResult
from argus_lite.modules.report.dedup import compute_summary

LEGAL_NOTICE = (
    "This report was generated by Argus Lite for authorized security testing only. "
    "Always obtain written permission before scanning any system you do not own."
)

_HTML_TEMPLATE = Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Argus Lite — {{ scan.target }}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 960px; margin: 0 auto; padding: 20px; background: #f8f9fa; color: #212529; }
  h1 { color: #1a1a2e; border-bottom: 2px solid #16213e; padding-bottom: 10px; }
  h2 { color: #16213e; margin-top: 30px; }
  table { border-collapse: collapse; width: 100%; margin: 15px 0; }
  th, td { border: 1px solid #dee2e6; padding: 8px 12px; text-align: left; }
  th { background: #16213e; color: white; }
  tr:nth-child(even) { background: #e9ecef; }
  .severity-info { background: #cce5ff; color: #004085; padding: 2px 8px; border-radius: 4px; font-weight: bold; }
  .severity-low { background: #fff3cd; color: #856404; padding: 2px 8px; border-radius: 4px; font-weight: bold; }
  .finding { border: 1px solid #dee2e6; border-radius: 8px; padding: 15px; margin: 10px 0; background: white; }
  .status-completed { color: #28a745; }
  .status-interrupted { color: #dc3545; }
  .status-failed { color: #dc3545; }
  .status-running { color: #ffc107; }
  .legal { background: #fff3cd; border: 1px solid #ffc107; border-radius: 8px; padding: 15px; margin-top: 30px; font-size: 0.9em; }
  .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; margin: 15px 0; }
  .summary-card { background: white; border: 1px solid #dee2e6; border-radius: 8px; padding: 15px; text-align: center; }
  .summary-card .value { font-size: 2em; font-weight: bold; color: #16213e; }
  .summary-card .label { font-size: 0.85em; color: #6c757d; }
</style>
</head>
<body>
<h1>Security Scan Report</h1>
<p><strong>Target:</strong> {{ scan.target }}<br>
<strong>Status:</strong> <span class="status-{{ scan.status }}">{{ scan.status }}</span><br>
{% if scan.started_at %}<strong>Date:</strong> {{ scan.started_at.strftime('%Y-%m-%d %H:%M UTC') }}<br>{% endif %}
{% if stats.duration_seconds > 0 %}<strong>Duration:</strong> {{ stats.duration_seconds | int }}s{% endif %}</p>

<h2>Summary</h2>
<div class="summary-grid">
  <div class="summary-card"><div class="value">{{ stats.open_ports }}</div><div class="label">Open Ports</div></div>
  <div class="summary-card"><div class="value">{{ stats.subdomains }}</div><div class="label">Subdomains</div></div>
  <div class="summary-card"><div class="value">{{ stats.technologies }}</div><div class="label">Technologies</div></div>
  <div class="summary-card"><div class="value">{{ stats.findings }}</div><div class="label">Findings</div></div>
</div>

{% if scan.recon.dns_records %}
<h2>DNS Records</h2>
<table>
<tr><th>Type</th><th>Name</th><th>Value</th><th>TTL</th></tr>
{% for r in scan.recon.dns_records %}
<tr><td>{{ r.type }}</td><td>{{ r.name }}</td><td>{{ r.value }}</td><td>{{ r.ttl }}</td></tr>
{% endfor %}
</table>
{% endif %}

{% if scan.analysis.open_ports %}
<h2>Open Ports</h2>
<table>
<tr><th>Port</th><th>Protocol</th><th>Service</th></tr>
{% for p in scan.analysis.open_ports %}
<tr><td>{{ p.port }}</td><td>{{ p.protocol }}</td><td>{{ p.service }}</td></tr>
{% endfor %}
</table>
{% endif %}

{% if scan.analysis.technologies %}
<h2>Technologies</h2>
<table>
<tr><th>Name</th><th>Version</th><th>Category</th></tr>
{% for t in scan.analysis.technologies %}
<tr><td>{{ t.name }}</td><td>{{ t.version }}</td><td>{{ t.category }}</td></tr>
{% endfor %}
</table>
{% endif %}

{% if scan.analysis.ssl_info %}
<h2>SSL/TLS</h2>
<table>
<tr><th>Protocol</th><th>Cipher</th><th>Issuer</th><th>Expired</th><th>Weak Cipher</th></tr>
<tr>
  <td>{{ scan.analysis.ssl_info.protocol }}</td>
  <td>{{ scan.analysis.ssl_info.cipher }}</td>
  <td>{{ scan.analysis.ssl_info.issuer }}</td>
  <td>{{ scan.analysis.ssl_info.expired }}</td>
  <td>{{ scan.analysis.ssl_info.weak_cipher }}</td>
</tr>
</table>
{% endif %}

{% if scan.findings %}
<h2>Findings</h2>
{% for f in scan.findings %}
<div class="finding">
  <span class="severity-{{ f.severity | lower }}">{{ f.severity }}</span>
  <strong>{{ f.title }}</strong>
  <p><strong>Asset:</strong> {{ f.asset }} | <strong>Source:</strong> {{ f.source }}</p>
  <p>{{ f.description }}</p>
  <p><strong>Evidence:</strong> {{ f.evidence }}</p>
  <p><strong>Remediation:</strong> {{ f.remediation }}</p>
</div>
{% endfor %}
{% endif %}

<div class="legal">{{ legal_notice }}</div>
</body>
</html>
""")


def generate_html_report(scan: ScanResult) -> str:
    """Generate an HTML report from ScanResult."""
    stats = compute_summary(scan)
    return _HTML_TEMPLATE.render(
        scan=scan,
        stats=stats,
        legal_notice=LEGAL_NOTICE,
    )


def write_html_report(scan: ScanResult, path: Path) -> None:
    """Write HTML report to file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_html_report(scan))
