"""HTML report generator using Jinja2."""

from __future__ import annotations

from pathlib import Path

from jinja2 import Template

from argus_lite.models.scan import ScanResult
from argus_lite.modules.report.dedup import compute_summary, filter_relevant_ports

LEGAL_NOTICE = (
    "This report was generated by Argus Lite for authorized security testing only. "
    "Always obtain written permission before scanning any system you do not own."
)

_HTML_TEMPLATE = Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Argus — {{ scan.target }}</title>
<style>
  :root { --bg: #0d1117; --card: #161b22; --border: #30363d; --text: #e6edf3; --dim: #8b949e; --accent: #58a6ff; --green: #3fb950; --yellow: #d29922; --red: #f85149; --orange: #db6d28; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; }
  .container { max-width: 1100px; margin: 0 auto; padding: 30px 20px; }

  /* Header */
  .header { border-bottom: 1px solid var(--border); padding-bottom: 24px; margin-bottom: 30px; }
  .header h1 { font-size: 28px; font-weight: 600; margin-bottom: 8px; }
  .header h1 span { color: var(--accent); }
  .meta { display: flex; gap: 20px; flex-wrap: wrap; color: var(--dim); font-size: 14px; }
  .meta span { display: flex; align-items: center; gap: 6px; }
  .status { padding: 2px 10px; border-radius: 20px; font-size: 12px; font-weight: 600; text-transform: uppercase; }
  .status-completed { background: rgba(63,185,80,0.15); color: var(--green); }
  .status-interrupted { background: rgba(248,81,73,0.15); color: var(--red); }
  .status-failed { background: rgba(248,81,73,0.15); color: var(--red); }
  .status-running { background: rgba(210,153,34,0.15); color: var(--yellow); }

  /* Summary Cards */
  .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 14px; margin-bottom: 30px; }
  .card { background: var(--card); border: 1px solid var(--border); border-radius: 10px; padding: 20px; text-align: center; }
  .card .num { font-size: 36px; font-weight: 700; color: var(--accent); }
  .card .label { font-size: 13px; color: var(--dim); margin-top: 4px; }
  .card.warn .num { color: var(--yellow); }
  .card.danger .num { color: var(--red); }
  .card.ok .num { color: var(--green); }

  /* Sections */
  .section { background: var(--card); border: 1px solid var(--border); border-radius: 10px; padding: 24px; margin-bottom: 20px; }
  .section h2 { font-size: 18px; font-weight: 600; margin-bottom: 16px; padding-bottom: 10px; border-bottom: 1px solid var(--border); }

  /* Tables */
  table { width: 100%; border-collapse: collapse; font-size: 14px; }
  th { text-align: left; padding: 10px 12px; background: rgba(110,118,129,0.1); color: var(--dim); font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
  td { padding: 10px 12px; border-top: 1px solid var(--border); }
  tr:hover td { background: rgba(110,118,129,0.05); }
  code { background: rgba(110,118,129,0.2); padding: 2px 6px; border-radius: 4px; font-size: 13px; }

  /* Findings */
  .finding { border: 1px solid var(--border); border-radius: 8px; padding: 16px 20px; margin-bottom: 12px; border-left: 4px solid var(--dim); }
  .finding.sev-info { border-left-color: var(--accent); }
  .finding.sev-low { border-left-color: var(--yellow); }
  .finding-header { display: flex; align-items: center; gap: 10px; margin-bottom: 8px; }
  .finding-title { font-weight: 600; font-size: 15px; }
  .badge { padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 700; text-transform: uppercase; }
  .badge-info { background: rgba(88,166,255,0.15); color: var(--accent); }
  .badge-low { background: rgba(210,153,34,0.15); color: var(--yellow); }
  .finding-meta { color: var(--dim); font-size: 13px; margin-bottom: 8px; }
  .finding-desc { margin-bottom: 8px; }
  .finding-fix { background: rgba(63,185,80,0.08); border: 1px solid rgba(63,185,80,0.2); border-radius: 6px; padding: 10px 14px; font-size: 13px; }
  .finding-fix strong { color: var(--green); }

  /* Security Headers */
  .header-status { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
  .header-ok { background: rgba(63,185,80,0.15); color: var(--green); }
  .header-missing { background: rgba(248,81,73,0.15); color: var(--red); }

  /* Collapsible */
  details { background: var(--card); border: 1px solid var(--border); border-radius: 10px; margin-bottom: 20px; }
  details summary { padding: 16px 24px; cursor: pointer; font-weight: 600; font-size: 16px; }
  details summary:hover { background: rgba(110,118,129,0.05); }
  details .content { padding: 0 24px 20px; }

  /* Footer */
  .legal { margin-top: 40px; padding: 16px 20px; background: rgba(210,153,34,0.08); border: 1px solid rgba(210,153,34,0.2); border-radius: 8px; color: var(--dim); font-size: 13px; }
  .footer { text-align: center; color: var(--dim); font-size: 12px; margin-top: 20px; padding: 20px; }
</style>
</head>
<body>
<div class="container">

<!-- Header -->
<div class="header">
  <h1>Security Report — <span>{{ scan.target }}</span></h1>
  <div class="meta">
    <span class="status status-{{ scan.status }}">{{ scan.status }}</span>
    {% if scan.started_at %}<span>{{ scan.started_at.strftime('%Y-%m-%d %H:%M UTC') }}</span>{% endif %}
    {% if stats.duration_seconds > 0 %}<span>{{ (stats.duration_seconds // 60) | int }}m {{ (stats.duration_seconds % 60) | int }}s</span>{% endif %}
    {% if scan.tools_used %}<span>Tools: {{ scan.tools_used | join(', ') }}</span>{% endif %}
  </div>
</div>

<!-- Summary Cards -->
<div class="cards">
  {% if stats.findings > 0 %}
  <div class="card warn"><div class="num">{{ stats.findings }}</div><div class="label">Findings</div></div>
  {% else %}
  <div class="card ok"><div class="num">0</div><div class="label">Findings</div></div>
  {% endif %}
  <div class="card {{ 'ok' if stats.security_headers_present >= 5 else 'warn' if stats.security_headers_present >= 3 else 'danger' }}">
    <div class="num">{{ stats.security_headers_present }}/{{ stats.security_headers_total }}</div>
    <div class="label">Security Headers</div>
  </div>
  {% if stats.open_ports %}<div class="card"><div class="num">{{ stats.open_ports }}</div><div class="label">Open Ports</div></div>{% endif %}
  {% if stats.technologies %}<div class="card"><div class="num">{{ stats.technologies }}</div><div class="label">Technologies</div></div>{% endif %}
  {% if stats.subdomains %}<div class="card"><div class="num">{{ stats.subdomains }}</div><div class="label">Subdomains</div></div>{% endif %}
</div>

<!-- AI Analysis -->
{% if scan.ai_analysis and scan.ai_analysis.executive_summary %}
<div class="section" style="border-left: 3px solid var(--accent);">
  <h2>AI Analysis <span style="font-size:12px;color:var(--dim);font-weight:normal;">{{ scan.ai_analysis.model_used }} | {{ scan.ai_analysis.tokens_used }} tokens</span></h2>
  <div style="background:rgba(88,166,255,0.08);border-radius:8px;padding:16px;margin-bottom:16px;">
    <p>{{ scan.ai_analysis.executive_summary }}</p>
  </div>
  {% if scan.ai_analysis.attack_chains %}
  <h3 style="margin-top:16px;font-size:15px;">Attack Chains</h3>
  {% for chain in scan.ai_analysis.attack_chains %}
  <div style="border:1px solid var(--border);border-radius:8px;padding:12px;margin:8px 0;">
    <strong>{{ chain.name }}</strong> <span class="badge badge-{{ chain.severity | lower if chain.severity in ['info','low'] else 'low' }}">{{ chain.severity }} / {{ chain.likelihood }}</span>
    <ol style="margin:8px 0 0 20px;color:var(--dim);">
      {% for step in chain.steps %}<li>{{ step }}</li>{% endfor %}
    </ol>
  </div>
  {% endfor %}
  {% endif %}
  {% if scan.ai_analysis.recommendations %}
  <h3 style="margin-top:16px;font-size:15px;">Recommendations</h3>
  <ul style="margin:8px 0 0 20px;">
    {% for rec in scan.ai_analysis.recommendations %}<li>{{ rec }}</li>{% endfor %}
  </ul>
  {% endif %}
  {% if scan.ai_analysis.trend_analysis %}
  <h3 style="margin-top:16px;font-size:15px;">Trend Analysis</h3>
  <p style="color:var(--dim);">{{ scan.ai_analysis.trend_analysis }}</p>
  {% endif %}
</div>
{% endif %}

<!-- Findings -->
{% if scan.findings %}
<div class="section">
  <h2>Findings</h2>
  {% for f in scan.findings %}
  <div class="finding sev-{{ f.severity | lower }}">
    <div class="finding-header">
      <span class="badge badge-{{ f.severity | lower }}">{{ f.severity }}</span>
      <span class="finding-title">{{ f.title }}</span>
    </div>
    <div class="finding-meta">{{ f.asset }} &middot; {{ f.source }}</div>
    <div class="finding-desc">{{ f.description }}</div>
    {% if f.evidence %}<div style="margin-bottom:8px"><code>{{ f.evidence }}</code></div>{% endif %}
    <div class="finding-fix"><strong>Fix:</strong> {{ f.remediation }}</div>
  </div>
  {% endfor %}
</div>
{% endif %}

<!-- Security Headers -->
{% if scan.analysis.security_headers %}
<div class="section">
  <h2>Security Headers</h2>
  <table>
    <tr><th>Header</th><th>Status</th></tr>
    {% for name, present in sec_headers %}
    <tr>
      <td>{{ name }}</td>
      <td><span class="header-status {{ 'header-ok' if present else 'header-missing' }}">{{ 'Present' if present else 'Missing' }}</span></td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endif %}

<!-- SSL/TLS -->
{% if scan.analysis.ssl_info and scan.analysis.ssl_info.protocol %}
<div class="section">
  <h2>SSL / TLS</h2>
  <table>
    <tr><th>Property</th><th>Value</th></tr>
    <tr><td>Protocol</td><td>{{ scan.analysis.ssl_info.protocol }}</td></tr>
    <tr><td>Cipher</td><td><code>{{ scan.analysis.ssl_info.cipher }}</code></td></tr>
    {% if scan.analysis.ssl_info.issuer %}<tr><td>Issuer</td><td>{{ scan.analysis.ssl_info.issuer }}</td></tr>{% endif %}
    {% if scan.analysis.ssl_info.not_after %}<tr><td>Expires</td><td>{{ scan.analysis.ssl_info.not_after }}</td></tr>{% endif %}
    {% if scan.analysis.ssl_info.expired %}<tr><td>Status</td><td><span class="header-status header-missing">EXPIRED</span></td></tr>{% endif %}
    {% if scan.analysis.ssl_info.weak_cipher %}<tr><td>Warning</td><td><span class="header-status header-missing">WEAK CIPHER</span></td></tr>{% endif %}
  </table>
</div>
{% endif %}

<!-- Technologies -->
{% if scan.analysis.technologies %}
<div class="section">
  <h2>Technologies</h2>
  <table>
    <tr><th>Technology</th><th>Version</th><th>Category</th></tr>
    {% for t in scan.analysis.technologies %}
    <tr><td>{{ t.name }}</td><td>{{ t.version or '-' }}</td><td>{{ t.category or '-' }}</td></tr>
    {% endfor %}
  </table>
</div>
{% endif %}

<!-- Open Ports (only with services) -->
{% if relevant_ports %}
<div class="section">
  <h2>Open Ports</h2>
  <table>
    <tr><th>Port</th><th>Protocol</th><th>Service</th></tr>
    {% for p in relevant_ports %}
    <tr><td>{{ p.port }}</td><td>{{ p.protocol }}</td><td>{{ p.service }}</td></tr>
    {% endfor %}
  </table>
</div>
{% endif %}

<!-- HTTP Probes -->
{% if scan.recon.http_probes %}
<div class="section">
  <h2>HTTP Probes</h2>
  <table>
    <tr><th>URL</th><th>Status</th><th>Title</th><th>Tech</th><th>Server</th><th>Response</th></tr>
    {% for p in scan.recon.http_probes %}
    <tr>
      <td><code>{{ p.url }}</code></td>
      <td>{{ p.status_code }}</td>
      <td>{{ p.title }}</td>
      <td>{{ p.tech | join(', ') }}</td>
      <td>{{ p.server }}</td>
      <td>{{ p.response_time_ms }}ms</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endif %}

<!-- Crawl Results -->
{% if scan.recon.crawl_results %}
<details>
  <summary>Crawled Endpoints ({{ scan.recon.crawl_results | length }})</summary>
  <div class="content">
    <table>
      <tr><th>URL</th><th>Method</th></tr>
      {% for c in scan.recon.crawl_results %}
      <tr><td><code>{{ c.url }}</code></td><td>{{ c.method }}</td></tr>
      {% endfor %}
    </table>
  </div>
</details>
{% endif %}

<!-- Historical URLs -->
{% if scan.recon.historical_urls %}
<details>
  <summary>Historical URLs ({{ scan.recon.historical_urls | length }})</summary>
  <div class="content">
    <table>
      <tr><th>URL</th><th>Source</th></tr>
      {% for h in scan.recon.historical_urls %}
      <tr><td><code>{{ h.url }}</code></td><td>{{ h.source }}</td></tr>
      {% endfor %}
    </table>
  </div>
</details>
{% endif %}

<!-- Fuzz Results -->
{% if scan.analysis.fuzz_results %}
<div class="section">
  <h2>Directory Fuzzing</h2>
  <table>
    <tr><th>URL</th><th>Status</th><th>Size</th><th>Words</th><th>Redirect</th></tr>
    {% for f in scan.analysis.fuzz_results %}
    <tr>
      <td><code>{{ f.url }}</code></td>
      <td>{{ f.status_code }}</td>
      <td>{{ f.content_length }}</td>
      <td>{{ f.words }}</td>
      <td>{{ f.redirect_location }}</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endif %}

<!-- TLS Certificates -->
{% if scan.recon.tls_certs %}
<details>
  <summary>TLS Certificates ({{ scan.recon.tls_certs | length }})</summary>
  <div class="content">
    <table>
      <tr><th>Host</th><th>Subject</th><th>Issuer</th><th>SAN</th><th>Expires</th></tr>
      {% for t in scan.recon.tls_certs %}
      <tr>
        <td>{{ t.host }}</td>
        <td>{{ t.subject_cn }}</td>
        <td>{{ t.issuer }}</td>
        <td>{{ t.san | join(', ') }}</td>
        <td>{{ t.not_after }}{{ ' (EXPIRED)' if t.expired else '' }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
</details>
{% endif %}

<!-- Screenshots -->
{% if scan.recon.screenshots %}
<div class="section">
  <h2>Screenshots</h2>
  <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:14px;">
    {% for s in scan.recon.screenshots %}
    <div style="background:var(--bg);border:1px solid var(--border);border-radius:8px;padding:12px;">
      <div style="font-weight:600;margin-bottom:4px;">{{ s.title or s.url }}</div>
      <div style="color:var(--dim);font-size:12px;margin-bottom:8px;"><code>{{ s.url }}</code> ({{ s.status_code }})</div>
      <img src="file://{{ s.screenshot_path }}" alt="{{ s.url }}" style="width:100%;border-radius:4px;border:1px solid var(--border);" onerror="this.style.display='none'">
    </div>
    {% endfor %}
  </div>
</div>
{% endif %}

<!-- Subdomains -->
{% if scan.recon.subdomains %}
<details>
  <summary>Subdomains ({{ scan.recon.subdomains | length }})</summary>
  <div class="content">
    <table>
      <tr><th>Subdomain</th><th>Source</th></tr>
      {% for s in scan.recon.subdomains %}
      <tr><td><code>{{ s.name }}</code></td><td>{{ s.source }}</td></tr>
      {% endfor %}
    </table>
  </div>
</details>
{% endif %}

<!-- DNS Records -->
{% if scan.recon.dns_records %}
<details>
  <summary>DNS Records ({{ scan.recon.dns_records | length }})</summary>
  <div class="content">
    <table>
      <tr><th>Type</th><th>Name</th><th>Value</th><th>TTL</th></tr>
      {% for r in scan.recon.dns_records %}
      <tr><td>{{ r.type }}</td><td>{{ r.name }}</td><td><code>{{ r.value }}</code></td><td>{{ r.ttl }}</td></tr>
      {% endfor %}
    </table>
  </div>
</details>
{% endif %}

<!-- WHOIS -->
{% if scan.recon.whois_info and scan.recon.whois_info.domain %}
<details>
  <summary>WHOIS — {{ scan.recon.whois_info.domain }}</summary>
  <div class="content">
    <table>
      <tr><th>Field</th><th>Value</th></tr>
      <tr><td>Registrar</td><td>{{ scan.recon.whois_info.registrar }}</td></tr>
      {% if scan.recon.whois_info.creation_date %}<tr><td>Created</td><td>{{ scan.recon.whois_info.creation_date }}</td></tr>{% endif %}
      {% if scan.recon.whois_info.expiration_date %}<tr><td>Expires</td><td>{{ scan.recon.whois_info.expiration_date }}</td></tr>{% endif %}
      {% if scan.recon.whois_info.name_servers %}<tr><td>Name Servers</td><td>{{ scan.recon.whois_info.name_servers | join(', ') }}</td></tr>{% endif %}
    </table>
  </div>
</details>
{% endif %}

<!-- Certificate -->
{% if scan.recon.certificate_info and scan.recon.certificate_info.subject %}
<details>
  <summary>Certificate — {{ scan.recon.certificate_info.subject }}</summary>
  <div class="content">
    <table>
      <tr><th>Field</th><th>Value</th></tr>
      <tr><td>Issuer</td><td>{{ scan.recon.certificate_info.issuer }}</td></tr>
      {% if scan.recon.certificate_info.not_before %}<tr><td>Valid from</td><td>{{ scan.recon.certificate_info.not_before }}</td></tr>{% endif %}
      {% if scan.recon.certificate_info.not_after %}<tr><td>Valid until</td><td>{{ scan.recon.certificate_info.not_after }}</td></tr>{% endif %}
      {% if scan.recon.certificate_info.san %}<tr><td>SAN</td><td>{{ scan.recon.certificate_info.san | join(', ') }}</td></tr>{% endif %}
    </table>
  </div>
</details>
{% endif %}

<!-- CVE Correlation -->
{% if scan.vulnerabilities %}
<div class="section">
  <h2>CVE Correlation</h2>
  <table>
    <thead><tr><th>CVE ID</th><th>CVSS Score</th><th>Vector</th></tr></thead>
    <tbody>
    {% for v in scan.vulnerabilities %}
    <tr>
      <td><a href="https://nvd.nist.gov/vuln/detail/{{ v.cve }}" target="_blank" style="color:var(--accent);">{{ v.cve }}</a></td>
      <td>{% if v.cvss_score is not none %}<span class="{{ 'header-missing' if v.cvss_score >= 7.0 else 'header-status' }}">{{ '%.1f' | format(v.cvss_score) }}</span>{% else %}-{% endif %}</td>
      <td><code style="font-size:11px;">{{ v.cvss_vector or '-' }}</code></td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endif %}

<!-- Errors -->
{% if scan.errors %}
<div class="section">
  <h2>Errors</h2>
  {% for err in scan.errors %}
  <div style="margin-bottom: 8px; color: var(--red);"><strong>{{ err.stage }}:</strong> {{ err.message }}</div>
  {% endfor %}
</div>
{% endif %}

<div class="legal">{{ legal_notice }}</div>
<div class="footer">Generated by Argus Lite v1.0</div>
</div>
</body>
</html>
""")


def generate_html_report(scan: ScanResult) -> str:
    """Generate an HTML report from ScanResult."""
    stats = compute_summary(scan)
    relevant_ports = filter_relevant_ports(scan)

    sec_headers = []
    sh = scan.analysis.security_headers
    if sh:
        sec_headers = [
            ("Strict-Transport-Security", sh.hsts),
            ("X-Frame-Options", sh.x_frame_options),
            ("X-Content-Type-Options", sh.x_content_type_options),
            ("Content-Security-Policy", sh.csp),
            ("X-XSS-Protection", sh.x_xss_protection),
            ("Referrer-Policy", sh.referrer_policy),
            ("Permissions-Policy", sh.permissions_policy),
        ]

    return _HTML_TEMPLATE.render(
        scan=scan,
        stats=stats,
        relevant_ports=relevant_ports,
        sec_headers=sec_headers,
        legal_notice=LEGAL_NOTICE,
    )


def write_html_report(scan: ScanResult, path: Path) -> None:
    """Write HTML report to file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_html_report(scan))
