"""JSON report generator."""

from __future__ import annotations

import json
from pathlib import Path

from argus_lite.models.scan import ScanResult
from argus_lite.modules.report.dedup import compute_summary, filter_relevant_ports

LEGAL_NOTICE = (
    "This report was generated by Argus Lite for authorized security testing only. "
    "Always obtain written permission before scanning any system you do not own."
)


def generate_json_report(scan: ScanResult) -> str:
    """Generate a JSON report string from ScanResult."""
    summary = compute_summary(scan)

    report = {
        "scan_id": scan.scan_id,
        "target": scan.target,
        "target_type": scan.target_type,
        "status": scan.status,
        "started_at": scan.started_at.isoformat() if scan.started_at else None,
        "completed_at": scan.completed_at.isoformat() if scan.completed_at else None,
        "summary": summary,
        "recon": scan.recon.model_dump(),
        "analysis": {
            **scan.analysis.model_dump(),
            "open_ports": [p.model_dump() for p in filter_relevant_ports(scan)],
        },
        "findings": [f.model_dump() for f in scan.findings],
        "tools_used": scan.tools_used,
        "completed_stages": scan.completed_stages,
        "skipped_stages": scan.skipped_stages,
        "legal_notice": LEGAL_NOTICE,
    }

    return json.dumps(report, indent=2, default=str, ensure_ascii=False)


def write_json_report(scan: ScanResult, path: Path) -> None:
    """Write JSON report to file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_json_report(scan))
