"""Markdown report generator."""

from __future__ import annotations

from pathlib import Path

from argus_lite.models.scan import ScanResult
from argus_lite.modules.report.dedup import compute_summary

LEGAL_NOTICE = (
    "> **LEGAL NOTICE:** This report was generated by Argus Lite for authorized "
    "security testing only. Always obtain written permission before scanning any "
    "system you do not own."
)


def generate_markdown_report(scan: ScanResult) -> str:
    """Generate a Markdown report from ScanResult."""
    stats = compute_summary(scan)
    lines: list[str] = []

    # Title
    lines.append("# Security Scan Report")
    lines.append(f"## Target: {scan.target}")
    lines.append(f"**Status:** {scan.status}")
    if scan.started_at:
        lines.append(f"**Date:** {scan.started_at.strftime('%Y-%m-%d %H:%M UTC')}")
    if stats["duration_seconds"] > 0:
        lines.append(f"**Duration:** {stats['duration_seconds']:.0f}s")
    lines.append("")

    # Summary table
    lines.append("## Summary")
    lines.append("| Metric | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| DNS Records | {stats['dns_records']} |")
    lines.append(f"| Subdomains | {stats['subdomains']} |")
    lines.append(f"| Open Ports | {stats['open_ports']} |")
    lines.append(f"| Technologies | {stats['technologies']} |")
    lines.append(f"| Findings (INFO) | {stats['info_count']} |")
    lines.append(f"| Findings (LOW) | {stats['low_count']} |")
    lines.append("")

    # DNS Records
    if scan.recon.dns_records:
        lines.append("## DNS Records")
        lines.append("| Type | Name | Value | TTL |")
        lines.append("|------|------|-------|-----|")
        for r in scan.recon.dns_records:
            lines.append(f"| {r.type} | {r.name} | {r.value} | {r.ttl} |")
        lines.append("")

    # Subdomains
    if scan.recon.subdomains:
        lines.append("## Subdomains")
        for s in scan.recon.subdomains:
            lines.append(f"- {s.name} (source: {s.source})")
        lines.append("")

    # Open Ports
    if scan.analysis.open_ports:
        lines.append("## Open Ports")
        lines.append("| Port | Protocol | Service |")
        lines.append("|------|----------|---------|")
        for p in scan.analysis.open_ports:
            lines.append(f"| {p.port} | {p.protocol} | {p.service} |")
        lines.append("")

    # Technologies
    if scan.analysis.technologies:
        lines.append("## Technologies")
        lines.append("| Name | Version | Category |")
        lines.append("|------|---------|----------|")
        for t in scan.analysis.technologies:
            lines.append(f"| {t.name} | {t.version} | {t.category} |")
        lines.append("")

    # SSL/TLS
    if scan.analysis.ssl_info:
        ssl = scan.analysis.ssl_info
        lines.append("## SSL/TLS")
        lines.append(f"- **Protocol:** {ssl.protocol}")
        lines.append(f"- **Cipher:** {ssl.cipher}")
        lines.append(f"- **Issuer:** {ssl.issuer}")
        if ssl.expired:
            lines.append("- **EXPIRED**")
        if ssl.weak_cipher:
            lines.append("- **WEAK CIPHER DETECTED**")
        lines.append("")

    # Findings
    if scan.findings:
        lines.append("## Findings")
        for f in scan.findings:
            lines.append(f"### [{f.severity}] {f.title}")
            lines.append(f"- **Asset:** {f.asset}")
            lines.append(f"- **Source:** {f.source}")
            lines.append(f"- **Description:** {f.description}")
            lines.append(f"- **Evidence:** {f.evidence}")
            lines.append(f"- **Remediation:** {f.remediation}")
            lines.append("")

    # Skipped stages
    if scan.skipped_stages:
        lines.append("## Skipped Stages")
        for stage in scan.skipped_stages:
            lines.append(f"- {stage}")
        lines.append("")

    # Legal notice
    lines.append("---")
    lines.append(LEGAL_NOTICE)
    lines.append("")

    return "\n".join(lines)


def write_markdown_report(scan: ScanResult, path: Path) -> None:
    """Write Markdown report to file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_markdown_report(scan))
