"""Markdown report generator."""

from __future__ import annotations

from pathlib import Path

from argus_lite.models.scan import ScanResult
from argus_lite.modules.report.dedup import compute_summary, filter_relevant_ports

LEGAL_NOTICE = (
    "> **LEGAL NOTICE:** This report was generated by Argus Lite for authorized "
    "security testing only. Always obtain written permission before scanning any "
    "system you do not own."
)


def generate_markdown_report(scan: ScanResult) -> str:
    """Generate a Markdown report from ScanResult."""
    stats = compute_summary(scan)
    lines: list[str] = []

    # Header
    lines.append("# Security Scan Report")
    lines.append(f"**Target:** `{scan.target}`")
    lines.append(f"**Status:** {scan.status}")
    if scan.started_at:
        lines.append(f"**Date:** {scan.started_at.strftime('%Y-%m-%d %H:%M UTC')}")
    if stats["duration_seconds"] > 0:
        m, s = divmod(int(stats["duration_seconds"]), 60)
        lines.append(f"**Duration:** {m}m {s}s")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    if stats["subdomains"]:
        lines.append(f"| Subdomains discovered | {stats['subdomains']} |")
    if stats["open_ports"]:
        lines.append(f"| Open ports | {stats['open_ports']} |")
    if stats["technologies"]:
        lines.append(f"| Technologies detected | {stats['technologies']} |")
    lines.append(f"| Security headers | {stats['security_headers_present']}/{stats['security_headers_total']} |")
    if stats["findings"]:
        lines.append(f"| Findings (INFO) | {stats['info_count']} |")
        lines.append(f"| Findings (LOW) | {stats['low_count']} |")
    else:
        lines.append("| Findings | None |")
    lines.append("")

    # Findings (most important — goes first)
    if scan.findings:
        lines.append("## Findings")
        lines.append("")
        for f in scan.findings:
            lines.append(f"### [{f.severity}] {f.title}")
            lines.append(f"**Asset:** `{f.asset}` | **Source:** {f.source}")
            lines.append("")
            lines.append(f"> {f.description}")
            lines.append("")
            if f.evidence:
                lines.append(f"**Evidence:** `{f.evidence}`")
            lines.append(f"**Remediation:** {f.remediation}")
            lines.append("")
            lines.append("---")
            lines.append("")

    # Security Headers
    sh = scan.analysis.security_headers
    if sh:
        lines.append("## Security Headers")
        lines.append("")
        lines.append("| Header | Status |")
        lines.append("|--------|--------|")
        _hdr = [
            ("Strict-Transport-Security", sh.hsts),
            ("X-Frame-Options", sh.x_frame_options),
            ("X-Content-Type-Options", sh.x_content_type_options),
            ("Content-Security-Policy", sh.csp),
            ("X-XSS-Protection", sh.x_xss_protection),
            ("Referrer-Policy", sh.referrer_policy),
            ("Permissions-Policy", sh.permissions_policy),
        ]
        for name, present in _hdr:
            icon = "Present" if present else "**MISSING**"
            lines.append(f"| {name} | {icon} |")
        lines.append("")

    # SSL/TLS
    ssl = scan.analysis.ssl_info
    if ssl and ssl.protocol:
        lines.append("## SSL/TLS")
        lines.append("")
        lines.append(f"| Property | Value |")
        lines.append(f"|----------|-------|")
        lines.append(f"| Protocol | {ssl.protocol} |")
        lines.append(f"| Cipher | `{ssl.cipher}` |")
        if ssl.issuer:
            lines.append(f"| Issuer | {ssl.issuer} |")
        if ssl.not_after:
            lines.append(f"| Expires | {ssl.not_after} |")
        if ssl.expired:
            lines.append(f"| **Status** | **EXPIRED** |")
        if ssl.weak_cipher:
            lines.append(f"| **Warning** | **WEAK CIPHER** |")
        lines.append("")

    # Technologies
    if scan.analysis.technologies:
        lines.append("## Technologies")
        lines.append("")
        lines.append("| Technology | Version | Category |")
        lines.append("|-----------|---------|----------|")
        for t in scan.analysis.technologies:
            ver = t.version or "-"
            cat = t.category or "-"
            lines.append(f"| {t.name} | {ver} | {cat} |")
        lines.append("")

    # Open Ports (only with services)
    relevant_ports = filter_relevant_ports(scan)
    if relevant_ports:
        lines.append("## Open Ports")
        lines.append("")
        lines.append("| Port | Protocol | Service |")
        lines.append("|------|----------|---------|")
        for p in relevant_ports:
            lines.append(f"| {p.port} | {p.protocol} | {p.service} |")
        lines.append("")

    # Subdomains
    if scan.recon.subdomains:
        lines.append("## Subdomains")
        lines.append("")
        for s in scan.recon.subdomains:
            lines.append(f"- `{s.name}` _{s.source}_")
        lines.append("")

    # DNS Records
    if scan.recon.dns_records:
        lines.append("<details>")
        lines.append("<summary><strong>DNS Records</strong> ({} records)</summary>".format(len(scan.recon.dns_records)))
        lines.append("")
        lines.append("| Type | Name | Value | TTL |")
        lines.append("|------|------|-------|-----|")
        for r in scan.recon.dns_records:
            lines.append(f"| {r.type} | {r.name} | `{r.value}` | {r.ttl} |")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    # Whois
    whois = scan.recon.whois_info
    if whois and whois.domain:
        lines.append("<details>")
        lines.append("<summary><strong>WHOIS Info</strong></summary>")
        lines.append("")
        lines.append(f"- **Domain:** {whois.domain}")
        lines.append(f"- **Registrar:** {whois.registrar}")
        if whois.creation_date:
            lines.append(f"- **Created:** {whois.creation_date}")
        if whois.expiration_date:
            lines.append(f"- **Expires:** {whois.expiration_date}")
        if whois.name_servers:
            lines.append(f"- **Name Servers:** {', '.join(whois.name_servers)}")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    # Certificate
    cert = scan.recon.certificate_info
    if cert and cert.subject:
        lines.append("<details>")
        lines.append("<summary><strong>Certificate Info</strong></summary>")
        lines.append("")
        lines.append(f"- **Subject:** {cert.subject}")
        lines.append(f"- **Issuer:** {cert.issuer}")
        if cert.not_before:
            lines.append(f"- **Valid from:** {cert.not_before}")
        if cert.not_after:
            lines.append(f"- **Valid until:** {cert.not_after}")
        if cert.san:
            lines.append(f"- **SAN:** {', '.join(cert.san[:10])}")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    # Skipped/errored stages
    if scan.skipped_stages:
        lines.append("## Skipped Stages")
        for stage in scan.skipped_stages:
            lines.append(f"- {stage}")
        lines.append("")

    if scan.errors:
        lines.append("## Errors")
        for err in scan.errors:
            lines.append(f"- **{err.stage}:** {err.message}")
        lines.append("")

    # Tools used
    if scan.tools_used:
        lines.append(f"*Tools: {', '.join(scan.tools_used)}*")
        lines.append("")

    # Legal
    lines.append("---")
    lines.append(LEGAL_NOTICE)
    lines.append("")

    return "\n".join(lines)


def write_markdown_report(scan: ScanResult, path: Path) -> None:
    """Write Markdown report to file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_markdown_report(scan))
