"""Agent Context — unified state for the autonomous pentesting agent."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import TYPE_CHECKING

from pydantic import BaseModel

from argus_lite.models.scan import ScanResult

if TYPE_CHECKING:
    from argus_lite.core.agent_memory import AgentMemory
    from argus_lite.core.skills import SkillRegistry, SkillResult


class AgentPlan(BaseModel):
    """Goal-based attack plan generated by LLM (linear, v3 compat)."""

    goal: str = ""
    steps: list[str] = []
    current_step: int = 0
    completed: list[str] = []
    failed: list[str] = []


class PlanNode(BaseModel):
    """A node in the plan tree — supports branching attack strategies."""

    id: str
    action: str                         # skill name or "branch" for branching
    description: str = ""
    condition: str = ""                 # "if IDOR found", "if tech=WordPress"
    children: list["PlanNode"] = []
    status: str = "pending"             # pending / completed / failed / skipped
    confidence: float = 0.5             # 0.0-1.0, higher = more promising
    result_summary: str = ""


class PlanTree(BaseModel):
    """Tree-based attack plan with branching strategies."""

    goal: str
    root: PlanNode

    def get_next_node(self) -> PlanNode | None:
        """DFS: find next pending node, prioritized by confidence."""
        candidates: list[PlanNode] = []
        self._collect_pending(self.root, candidates)
        if not candidates:
            return None
        candidates.sort(key=lambda n: n.confidence, reverse=True)
        return candidates[0]

    def _collect_pending(self, node: PlanNode, out: list[PlanNode]) -> None:
        if node.status == "pending" and node.action != "branch":
            out.append(node)
        for child in node.children:
            self._collect_pending(child, out)

    def mark_completed(self, node_id: str, summary: str = "") -> None:
        node = self._find(self.root, node_id)
        if node:
            node.status = "completed"
            node.result_summary = summary

    def mark_failed(self, node_id: str, error: str = "") -> None:
        node = self._find(self.root, node_id)
        if node:
            node.status = "failed"
            node.result_summary = error

    def add_branch(self, parent_id: str, new_node: PlanNode) -> None:
        parent = self._find(self.root, parent_id)
        if parent:
            parent.children.append(new_node)

    def _find(self, node: PlanNode, node_id: str) -> PlanNode | None:
        if node.id == node_id:
            return node
        for child in node.children:
            found = self._find(child, node_id)
            if found:
                return found
        return None

    def to_llm_context(self) -> str:
        """Render plan tree for LLM prompt."""
        lines = [f"Plan goal: {self.goal}"]
        self._render(self.root, lines, indent=0)
        return "\n".join(lines)

    def _render(self, node: PlanNode, lines: list[str], indent: int) -> None:
        prefix = "  " * indent
        status_icon = {"pending": "○", "completed": "✓", "failed": "✗", "skipped": "—"}.get(node.status, "?")
        lines.append(f"{prefix}{status_icon} {node.action} (conf={node.confidence:.1f}) {node.result_summary}")
        for child in node.children:
            self._render(child, lines, indent + 1)


class AgentStep(BaseModel):
    """Record of a single agent decision + execution."""

    step_number: int
    thought: str = ""
    action: str = ""
    params: dict = {}
    result_summary: str = ""
    result_success: bool = True
    findings_count: int = 0
    timestamp: datetime = None

    def __init__(self, **data):
        if "timestamp" not in data or data["timestamp"] is None:
            data["timestamp"] = datetime.now(tz=timezone.utc)
        super().__init__(**data)


class AgentResult(BaseModel):
    """Final result of an agent run."""

    target: str
    scan_result: ScanResult | None = None
    plan: AgentPlan | None = None
    steps: list[AgentStep] = []
    total_findings: int = 0
    skills_used: list[str] = []


class AgentContext:
    """Mutable state for the agent session."""

    def __init__(
        self,
        target: str,
        scan_result: ScanResult | None = None,
        skill_registry: "SkillRegistry | None" = None,
        memory: "AgentMemory | None" = None,
        environment: "Any | None" = None,
        stealth: "Any | None" = None,
    ) -> None:
        self.target = target
        self.environment = environment  # EnvironmentProfile
        self.stealth = stealth          # StealthConfig
        self.attack_chains_context: str = ""  # from AttackGraph
        self.intelligence_context: str = ""   # from KB + Meta + TargetScorer
        self.scored_targets: list = []        # from TargetScorer
        self.http_session: "Any | None" = None  # HttpSessionManager
        self.scan_result = scan_result or ScanResult(
            scan_id="agent", target=target, target_type="domain",
            status="running", started_at=datetime.now(tz=timezone.utc),
        )
        self.plan: AgentPlan | None = None
        self.history: list[AgentStep] = []
        self.skill_registry = skill_registry
        self.memory = memory

    def update_from_result(self, skill_name: str, result: "SkillResult") -> None:
        """Update scan_result with findings from a skill execution."""
        if result.findings:
            self.scan_result.findings.extend(result.findings)

    def build_llm_context(self) -> str:
        """Build context string for LLM decision-making."""
        lines = [f"Target: {self.target}"]

        # Tech stack
        techs = self.scan_result.analysis.technologies
        if techs:
            lines.append(f"Tech: {', '.join(t.name + (' ' + t.version if t.version else '') for t in techs[:10])}")

        # Open ports
        ports = self.scan_result.analysis.open_ports
        if ports:
            lines.append(f"Ports: {', '.join(str(p.port) for p in ports[:15])}")

        # Crawled URLs
        urls = self.scan_result.recon.crawl_results
        if urls:
            lines.append(f"Crawled URLs ({len(urls)}):")
            for c in urls[:15]:
                lines.append(f"  {c.url}")

        # Current findings
        if self.scan_result.findings:
            lines.append(f"Findings ({len(self.scan_result.findings)}):")
            for f in self.scan_result.findings[:10]:
                lines.append(f"  [{f.severity}] {f.title}")

        # Plan status
        if self.plan:
            lines.append(f"\nPlan goal: {self.plan.goal}")
            lines.append(f"Completed: {', '.join(self.plan.completed) or 'none'}")
            if self.plan.failed:
                lines.append(f"Failed: {', '.join(self.plan.failed)}")
            remaining = [s for s in self.plan.steps if s not in self.plan.completed and s not in self.plan.failed]
            if remaining:
                lines.append(f"Remaining: {', '.join(remaining[:5])}")

        # Recent history (last 5 steps)
        if self.history:
            lines.append("\nRecent actions:")
            for h in self.history[-5:]:
                status = "OK" if h.result_success else "FAIL"
                lines.append(f"  Step {h.step_number}: {h.action} → {status}: {h.result_summary[:80]}")

        # Memory context
        if self.memory:
            mem_ctx = self.memory.get_context_for_target(self.target)
            if mem_ctx:
                lines.append(f"\nMemory: {mem_ctx}")

        # Environment awareness
        if self.environment:
            env = self.environment
            env_parts = []
            if env.waf_detected:
                env_parts.append(f"WAF: {env.waf_type or 'detected'}")
            if env.cdn:
                env_parts.append(f"CDN: {env.cdn}")
            if env.server:
                env_parts.append(f"Server: {env.server}")
            if env.anti_bot:
                env_parts.append("Anti-bot: active")
            if env_parts:
                lines.append(f"\nEnvironment: {', '.join(env_parts)}")

        # Stealth mode
        if self.stealth and self.stealth.enabled:
            lines.append(f"Stealth: ON (delay={self.stealth.delay_ms}ms)")

        # Attack chains (from graph search)
        if self.attack_chains_context:
            lines.append(f"\n{self.attack_chains_context}")

        # Intelligence context (knowledge base + meta-learning + target scoring)
        if self.intelligence_context:
            lines.append(f"\n{self.intelligence_context}")

        # Available skills
        if self.skill_registry:
            available = [s.name for s in self.skill_registry.list_available()]
            lines.append(f"\nAvailable skills: {', '.join(available)}")

        return "\n".join(lines)
