"""Agent Context — unified state for the autonomous pentesting agent."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import TYPE_CHECKING

from pydantic import BaseModel

from argus_lite.models.scan import ScanResult

if TYPE_CHECKING:
    from argus_lite.core.agent_memory import AgentMemory
    from argus_lite.core.skills import SkillRegistry, SkillResult


class AgentPlan(BaseModel):
    """Goal-based attack plan generated by LLM."""

    goal: str = ""
    steps: list[str] = []
    current_step: int = 0
    completed: list[str] = []
    failed: list[str] = []


class AgentStep(BaseModel):
    """Record of a single agent decision + execution."""

    step_number: int
    thought: str = ""
    action: str = ""
    params: dict = {}
    result_summary: str = ""
    result_success: bool = True
    findings_count: int = 0
    timestamp: datetime = None

    def __init__(self, **data):
        if "timestamp" not in data or data["timestamp"] is None:
            data["timestamp"] = datetime.now(tz=timezone.utc)
        super().__init__(**data)


class AgentResult(BaseModel):
    """Final result of an agent run."""

    target: str
    scan_result: ScanResult | None = None
    plan: AgentPlan | None = None
    steps: list[AgentStep] = []
    total_findings: int = 0
    skills_used: list[str] = []


class AgentContext:
    """Mutable state for the agent session."""

    def __init__(
        self,
        target: str,
        scan_result: ScanResult | None = None,
        skill_registry: "SkillRegistry | None" = None,
        memory: "AgentMemory | None" = None,
    ) -> None:
        self.target = target
        self.scan_result = scan_result or ScanResult(
            scan_id="agent", target=target, target_type="domain",
            status="running", started_at=datetime.now(tz=timezone.utc),
        )
        self.plan: AgentPlan | None = None
        self.history: list[AgentStep] = []
        self.skill_registry = skill_registry
        self.memory = memory

    def update_from_result(self, skill_name: str, result: "SkillResult") -> None:
        """Update scan_result with findings from a skill execution."""
        if result.findings:
            self.scan_result.findings.extend(result.findings)

    def build_llm_context(self) -> str:
        """Build context string for LLM decision-making."""
        lines = [f"Target: {self.target}"]

        # Tech stack
        techs = self.scan_result.analysis.technologies
        if techs:
            lines.append(f"Tech: {', '.join(t.name + (' ' + t.version if t.version else '') for t in techs[:10])}")

        # Open ports
        ports = self.scan_result.analysis.open_ports
        if ports:
            lines.append(f"Ports: {', '.join(str(p.port) for p in ports[:15])}")

        # Crawled URLs
        urls = self.scan_result.recon.crawl_results
        if urls:
            lines.append(f"Crawled URLs ({len(urls)}):")
            for c in urls[:15]:
                lines.append(f"  {c.url}")

        # Current findings
        if self.scan_result.findings:
            lines.append(f"Findings ({len(self.scan_result.findings)}):")
            for f in self.scan_result.findings[:10]:
                lines.append(f"  [{f.severity}] {f.title}")

        # Plan status
        if self.plan:
            lines.append(f"\nPlan goal: {self.plan.goal}")
            lines.append(f"Completed: {', '.join(self.plan.completed) or 'none'}")
            if self.plan.failed:
                lines.append(f"Failed: {', '.join(self.plan.failed)}")
            remaining = [s for s in self.plan.steps if s not in self.plan.completed and s not in self.plan.failed]
            if remaining:
                lines.append(f"Remaining: {', '.join(remaining[:5])}")

        # Recent history (last 5 steps)
        if self.history:
            lines.append("\nRecent actions:")
            for h in self.history[-5:]:
                status = "OK" if h.result_success else "FAIL"
                lines.append(f"  Step {h.step_number}: {h.action} → {status}: {h.result_summary[:80]}")

        # Memory context
        if self.memory:
            mem_ctx = self.memory.get_context_for_target(self.target)
            if mem_ctx:
                lines.append(f"\nMemory: {mem_ctx}")

        # Available skills
        if self.skill_registry:
            available = [s.name for s in self.skill_registry.list_available()]
            lines.append(f"\nAvailable skills: {', '.join(available)}")

        return "\n".join(lines)
